language: python
python:
  - '3.6'
install:
  - pip install -r requirements.txt
script:
  - bash ./deploy.sh
# Specify global variables for TravisCI to set before anything happens
env:
  global:
    - ENCRYPTION_LABEL: "389c70d48525"
    - COMMIT_AUTHOR_EMAIL: "brookskindle+git@gmail.com"
    - FLASK_APP: "app.py"
# Only kick off a TravisCI deploy on the given branches
branches:
  only:
    - master
